version: 2.1
jobs:
  build:
    docker:
      - image: cypress/included:4.6.0
        environment:
          ## this enables colors in the output
          TERM: xterm
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      
      - run:
          name: Run Cypress tests
          command: npm run cy:ci